# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 622)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(5.0)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"\n"
"   border-top: 3px solid #79c0fa;\n"
"    border-radius: 8px;\n"
"    border-top-left-radius: 0px;\n"
"   border-top-right-radius: 0px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
" border: 1px solid #79c0fa;\n"
"border-bottom: none;\n"
"border-radius: 10px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #0c8eee;\n"
"    border: 1px solid #0c8eee;\n"
"    \n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"     background: #79c0fa;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"   background: #63b7fc;\n"
"    border: #63b7fc;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 7ex;\n"
"    margin-right: 2px;\n"
"    padding: 3px 16px 2px 16px;\n"
"}\n"
"")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Uzbek, QtCore.QLocale.Uzbekistan))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setStyleSheet("QSplitter::handle#splitter{\n"
"background:qlineargradient(spread:reflect, x1:0.496, y1:0, x2:1, y2:0, stop:0 rgba(124, 208, 239, 255), stop:0.113636 rgba(255, 255, 255, 255), stop:0.219101 rgba(124, 208, 239, 255), stop:0.308989 rgba(255, 255, 255, 255), stop:0.426136 rgba(124, 208, 239, 255), stop:0.511236 rgba(255, 255, 255, 255), stop:0.586892 rgba(124, 208, 239, 255), stop:0.668539 rgba(255, 255, 255, 255), stop:0.775281 rgba(124, 208, 239, 255), stop:0.853933 rgba(255, 255, 255, 255), stop:0.966292 rgba(124, 208, 239, 255));\n"
"border: 2px solid rgb(240, 240, 240);\n"
"}")
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(2)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 246))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox#groupBox_2{\n"
"    margin-top: 1.3em;\n"
" border: 1px solid #7cd0ef;\n"
"border-radius: 10px;\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"\n"
"QGroupBox::title#groupBox_2{\n"
"subcontrol-position: top center;\n"
"subcontrol-origin: margin;\n"
"padding: 1px 5px 0 5px;\n"
"background-color: rgb(250, 250, 250);\n"
"border-radius: 10px;\n"
"border: 1px solid #7cd0ef;\n"
"border-bottom: none;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(5, 8, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.splitter_2)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget_2.setAutoFillBackground(False)
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setMidLineWidth(0)
        self.tableWidget_2.setAutoScroll(True)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/male.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon1)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/female.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon2)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(218, 215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"   margin-top: 0.7em;\n"
"border: none;\n"
"}\n"
"QGroupBox::title{\n"
"    top: -3px;\n"
"subcontrol-origin: margin;\n"
"padding: 0 5px 0 5px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #add1f6;")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_9.addWidget(self.lineEdit_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.line_7 = QtWidgets.QFrame(self.groupBox_3)
        self.line_7.setStyleSheet("")
        self.line_7.setLineWidth(1)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #add1f6;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #add1f6;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #add1f6;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(240, 215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"   margin-top: 0.7em;\n"
"border: none;\n"
"}\n"
"QGroupBox::title{\n"
"    top: -3px;\n"
"subcontrol-origin: margin;\n"
"padding: 0 5px 0 5px;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit{border-radius: 5px;\n"
"border: 1px solid #add1f6;\n"
"}\n"
"QLineEdit:hover{\n"
"border-color: rgb(90, 170, 255);\n"
"}")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_10.addWidget(self.lineEdit_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.line_6 = QtWidgets.QFrame(self.groupBox_5)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{border-radius: 5px;\n"
"border: 1px solid #add1f6;\n"
"}\n"
"QLineEdit:hover{\n"
"border-color: rgb(90, 170, 255);\n"
"}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_7.addWidget(self.lineEdit_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_4 = QtWidgets.QFrame(self.groupBox_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit{border-radius: 5px;\n"
"border: 1px solid #add1f6;\n"
"}\n"
"QLineEdit:hover{\n"
"border-color: rgb(90, 170, 255);\n"
"}")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_8.addWidget(self.lineEdit_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox::title#groupBox{\n"
"subcontrol-position: top center;\n"
"subcontrol-origin: margin;\n"
"padding: 1px 5px 0 5px;\n"
"background-color: rgb(250, 250, 250);\n"
"border-radius: 10px;\n"
"border: 1px solid #7cd0ef;\n"
"border-bottom: none;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"QGroupBox#groupBox{\n"
"    margin-top: 1.3em;\n"
" border: 1px solid #7cd0ef;\n"
"border-radius: 10px;\n"
"background-color: rgb(250, 250, 250);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(5, 5, 5, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 32))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-right: 0px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-left-radius:10px;\n"
"\n"
"}")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(240, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left: 0px;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"QLineEdit::hover{\n"
"border: 1px solid #29f9ff;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"QLineEdit::focus{\n"
"border: 1px solid #29e1ff;\n"
"}")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(106, 28))
        self.comboBox.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid #7cd0ef;\n"
"    border-radius: 3px;\n"
"    min-width: 8em;\n"
"}\n"
"QComboBox:hover{\n"
"border-color: #5487ee;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 18px;\n"
" \n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"  image:  url(:/Icons/Icons/drop-down-arrow.png);\n"
"width: 20px;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"    /* Does this work with QDateEdit??? */\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d8d7d7, stop: 1 #e9e9e9);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(18, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox::indicator:unchecked{\n"
"     image: url(:/Icons/Icons/unchecked.png);\n"
" }\n"
"QCheckBox::indicator:unchecked:hover{\n"
"     image: url(:/Icons/Icons/unchecked_hover.png);\n"
" }\n"
"QCheckBox::indicator:checked{\n"
"     image: url(:/Icons/Icons/checked.png);\n"
" }\n"
"QCheckBox::indicator:checked:hover{\n"
"     image: url(:/Icons/Icons/checked_hover.png);\n"
" }")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setMinimumSize(QtCore.QSize(85, 32))
        self.pushButton_7.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_6.setMaximumSize(QtCore.QSize(105, 32))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/delete_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/qr.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/add_class.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMinimumSize(QtCore.QSize(85, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        font.setItalic(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/add_pupil.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/pupils.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon9, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_3.setStyleSheet("QSplitter::handle#splitter_3{\n"
"background:qlineargradient(spread:reflect, x1:0.496, y1:0, x2:1, y2:0, stop:0 rgba(124, 208, 239, 255), stop:0.113636 rgba(255, 255, 255, 255), stop:0.219101 rgba(124, 208, 239, 255), stop:0.308989 rgba(255, 255, 255, 255), stop:0.426136 rgba(124, 208, 239, 255), stop:0.511236 rgba(255, 255, 255, 255), stop:0.586892 rgba(124, 208, 239, 255), stop:0.668539 rgba(255, 255, 255, 255), stop:0.775281 rgba(124, 208, 239, 255), stop:0.853933 rgba(255, 255, 255, 255), stop:0.966292 rgba(124, 208, 239, 255));\n"
"border: 2px solid rgb(240, 240, 240);\n"
"}")
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setHandleWidth(2)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"   margin-top: 1em;\n"
"border: 1px solid #7cd0ef;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"QGroupBox::title{\n"
"  top: -2px;\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
"padding: 0 5px 5px 5px;\n"
"background: rgb(250, 250, 250);\n"
"border: 1px solid #7cd0ef;\n"
"border-radius: 8px;\n"
"border-bottom-left-radius: 12px;\n"
"border-bottom-right-radius: 12px;\n"
"border-bottom: none;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("")
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setAlternatingRowColors(False)
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_3.horizontalHeader().setHighlightSections(False)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_6.addWidget(self.tableWidget_3, 1, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"   margin-top: 1em;\n"
"border: 1px solid #7cd0ef;\n"
"border-left: none;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"QGroupBox::title{\n"
"  top: -2px;\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
"padding: 0 5px 5px 5px;\n"
"background: rgb(250, 250, 250);\n"
"border: 1px solid #7cd0ef;\n"
"border-radius: 8px;\n"
"border-bottom-left-radius: 12px;\n"
"border-bottom-right-radius: 12px;\n"
"border-bottom: none;\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setStyleSheet("")
        self.tableWidget_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setAlternatingRowColors(False)
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_4.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_4.setRowCount(0)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/came.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/leave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":/Icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon12)
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setHighlightSections(False)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.tableWidget_4, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_6)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 3)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("QGroupBox::title{\n"
"subcontrol-position: top center;\n"
"subcontrol-origin: margin;\n"
"padding: 0px 5px 0 5px;\n"
"background-color: rgb(250, 250, 250);\n"
"border-radius: 10px;\n"
"border: 1px solid #7cd0ef;\n"
"border-bottom: none;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"}\n"
"QGroupBox{\n"
"    margin-top: 1.3em;\n"
" border: 1px solid #7cd0ef;\n"
"border-radius: 10px;\n"
"background-color: rgb(250, 250, 250);\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setContentsMargins(5, -1, 5, 5)
        self.gridLayout_4.setHorizontalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setStyleSheet("")
        self.tableWidget_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_5.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_5.setAlternatingRowColors(False)
        self.tableWidget_5.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_5.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_5.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_5.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget_5.horizontalHeader().setHighlightSections(False)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(60)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setMinimumSize(QtCore.QSize(250, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 2px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_12.addWidget(self.pushButton_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setMinimumSize(QtCore.QSize(250, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 2px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit_time.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_8.setIcon(icon13)
        self.pushButton_8.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_10.setMinimumSize(QtCore.QSize(250, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 2px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid #50A5FF;\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_10.setIcon(icon14)
        self.pushButton_10.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_12.addWidget(self.pushButton_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addWidget(self.splitter_3)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/calendar2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon15, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16))
        self.frame.setStyleSheet("border-top: 1px solid rgba(124, 208, 239, 0.5);\n"
"border-bottom: 1px solid rgba(124, 208, 239, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_3.setStretch(0, 80)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_6.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 23))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"background-color: #9ED6EC;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_14.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(543, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 79, 116);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        spacerItem7 = QtWidgets.QSpacerItem(1111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_12.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_12.setStyleSheet("QPushButton\n"
"                   {\n"
"                   font-family:\"Webdings\";\n"
"                   text-align:top;\n"
"                   background:#9ED6EC;\n"
"                   border:none;\n"
"                   font-size:16px;\n"
"                    color: white;\n"
"                   }\n"
"QPushButton:hover\n"
"{\n"
"background: #6db2cd;\n"
"}")
        self.pushButton_12.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_13.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_13.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_13.setStyleSheet("QPushButton\n"
"                   {\n"
"                   font-family:\"Webdings\";\n"
"                   text-align:top;\n"
"                   background:#9ED6EC;\n"
"                   border:none;\n"
"                   font-size:18px;\n"
"                    color: white;\n"
"                   }\n"
"QPushButton:hover\n"
"{\n"
"background: #6db2cd;\n"
"}")
        self.pushButton_13.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_13.addWidget(self.pushButton_13)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_4.setMaximumSize(QtCore.QSize(24, 23))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton\n"
"                   {\n"
"                   font-family:\"Webdings\";\n"
"                   text-align:top;\n"
"                   background:#9ED6EC;\n"
"                   border:none;\n"
"                   font-size:15px;\n"
"                    color: white;\n"
"                   }\n"
"QPushButton:hover{\n"
"background: #ec1c24;\n"
"}")
        self.pushButton_4.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_13.addWidget(self.pushButton_4)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14.setStretch(0, 11)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 10)
        self.horizontalLayout_14.setStretch(3, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SControl"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sinflar ro\'yxati"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sinf"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sinf rahbari"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jami o\'quvchilar"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "O\'g\'il bolalar"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Qiz bolalar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Umumiy ma\'lumot:"))
        self.label_7.setText(_translate("MainWindow", "Sinflar:"))
        self.label.setText(_translate("MainWindow", "O\'quvchilar:"))
        self.label_2.setText(_translate("MainWindow", "O\'gil bolalar:"))
        self.label_3.setText(_translate("MainWindow", "Qiz bolalar:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Maktab haqida:"))
        self.label_8.setText(_translate("MainWindow", "Viloyat:"))
        self.label_5.setText(_translate("MainWindow", "Tuman:"))
        self.label_6.setText(_translate("MainWindow", "Maktab:"))
        self.groupBox.setTitle(_translate("MainWindow", "O\'quvchilar ro\'yxati"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Qidirish..."))
        self.checkBox.setText(_translate("MainWindow", "Rasmi"))
        self.pushButton_7.setText(_translate("MainWindow", " Tahrir"))
        self.pushButton_6.setText(_translate("MainWindow", "O\'chirish"))
        self.pushButton_5.setText(_translate("MainWindow", "Qr Karta"))
        self.pushButton_3.setText(_translate("MainWindow", "Yangi\n"
"  sinf"))
        self.pushButton_2.setText(_translate("MainWindow", "Yangi\n"
"o\'quvchi"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rasmi"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Guruhi"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ismi"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Familiyasi"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Otasining ismi"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Onasining ismi"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Jinsi"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Tug\'ilgan kuni"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Telefon nomeri"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Passport seriyasi"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Telegram id"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Manzili"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "O\'quvchilar"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sinflar"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sinf nomi"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sinf raxbari"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Status"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sanalar"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Keldi"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ketdi"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hozirda"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Davomat"))
        self.pushButton_9.setText(_translate("MainWindow", "Sanani o\'chirish"))
        self.pushButton_8.setText(_translate("MainWindow", "Tahrirlash"))
        self.pushButton_10.setText(_translate("MainWindow", "Kamera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Davomat"))
        self.label_4.setText(_translate("MainWindow", "Time"))
        self.label_9.setText(_translate("MainWindow", " SControl"))
        self.pushButton_12.setText(_translate("MainWindow", "0"))
        self.pushButton_13.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "r"))
import Res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
