# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 158)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(455, 158))
        MainWindow.setMaximumSize(QtCore.QSize(455, 158))
        MainWindow.setSizeIncrement(QtCore.QSize(450, 90))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"border: 1px solid #7cd0ef;\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(20, 30))
        self.pushButton.setStyleSheet("background: transparent;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/came.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(18, 18))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setMinimumSize(QtCore.QSize(80, 30))
        self.timeEdit.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("QTimeEdit{border-radius: 2px;\n"
"border: 1px solid #7cd0ef;\n"
"border-radius: 5px;\n"
"}\n"
"QTimeEdit:hover{\n"
"border-color: #5487ee;\n"
"}\n"
"\n"
"\n"
"")
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setKeyboardTracking(True)
        self.timeEdit.setProperty("showGroupSeparator", True)
        self.timeEdit.setCalendarPopup(True)
        self.timeEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_5.addWidget(self.timeEdit)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setMinimumSize(QtCore.QSize(20, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(20, 25))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"}\n"
"QPushButton::hover{\n"
"border-radius: 5px;\n"
"background: rgba(58, 247, 240, 0.1);\n"
"}\n"
"QPushButton::pressed{\n"
"background: rgba(58, 247, 240, 0.2);\n"
"}")
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/cancel2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(185, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 2px solid rgb(47, 231, 247);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 8)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"border: 1px solid #7cd0ef;\n"
"border-left: none;\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(20, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 30))
        self.pushButton_2.setStyleSheet("background: transparent;")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/leave.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.groupBox_2)
        self.timeEdit_2.setMinimumSize(QtCore.QSize(80, 30))
        self.timeEdit_2.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.timeEdit_2.setFont(font)
        self.timeEdit_2.setStyleSheet("QTimeEdit{border-radius: 2px;\n"
"border: 1px solid #7cd0ef;\n"
"border-radius: 5px;\n"
"}\n"
"QTimeEdit:hover{\n"
"border-color: #5487ee;\n"
"}\n"
"\n"
"\n"
"")
        self.timeEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit_2.setKeyboardTracking(True)
        self.timeEdit_2.setProperty("showGroupSeparator", True)
        self.timeEdit_2.setCalendarPopup(True)
        self.timeEdit_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.horizontalLayout.addWidget(self.timeEdit_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(20, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(20, 25))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"}\n"
"QPushButton::hover{\n"
"border-radius: 5px;\n"
"background: rgba(58, 247, 240, 0.1);\n"
"}\n"
"QPushButton::pressed{\n"
"background: rgba(58, 247, 240, 0.2);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_4.setMaximumSize(QtCore.QSize(185, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 2px solid rgb(47, 231, 247);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 8)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"border: 1px solid #7cd0ef;\n"
"border-top: none;\n"
"\n"
"}\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 2px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 2px solid rgb(47, 231, 247);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 2px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 2px solid rgb(47, 231, 247);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vaqtni o\'rnatish"))
        self.label.setText(_translate("MainWindow", "Keldi:"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "h:mm"))
        self.pushButton_3.setText(_translate("MainWindow", "Hozirgi vaqt"))
        self.label_2.setText(_translate("MainWindow", "Ketdi:"))
        self.timeEdit_2.setDisplayFormat(_translate("MainWindow", "h:mm"))
        self.pushButton_4.setText(_translate("MainWindow", "Hozirgi vaqt"))
        self.pushButton_5.setText(_translate("MainWindow", "   Bekor qilish"))
        self.pushButton_8.setText(_translate("MainWindow", "  Tasdiqlash"))
import Res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
